"""empty message

Revision ID: cb13678af16f
Revises: 
Create Date: 2024-11-10 16:37:29.143068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb13678af16f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_services', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('repair_services', 'tracking_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repair_services', 'tracking_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('repair_services', 'created_at')
    # ### end Alembic commands ###
